#!/bin/bash


for file in `ls ref/*.xml`;
do
    name=`echo "${file%%.*}.sqlite"`
    out=`echo "${file%%.*}.output"`
    log=`echo "${file%%.*}.log"`
    rm $name $out $log
    cyclus $file -o $name -v6 | tee $out
    
    echo "Feed Assay:" >> $log
    grep -F "* Feed Assay:" $out | tail -5 | cut -d " " -f16- >> $log
    echo "Product Assay:" >> $log
    grep -F "* Product Assay:" $out | tail -5 | cut -d " " -f16- >> $log
    echo "Tails Assay:" >> $log
    grep -F "* Tails Assay:" $out | tail -5 | cut -d " " -f16- >> $log
done
